### ISSUE TITLE
OS X Yosemite Python 2.7.x 

### ISSUE THREAD

**Issue by helio58** [deltaflyer4747/Xiaomi_Yi#10]
Hi, thanks for this app. I used it in VM ware machine and works perfectly.

My problem is in the Mac when I run the CC.pyw it does not open the  app.
Any tips what i m doing wrong?

Thanks
Jose

**Comment by deltaflyer4747** [comment]
rename .pyw to .py and see the output - i need the traceback

**Comment by helio58** [comment]
Thanks dettaflyer4747 , I found the error wrong file association now its working .Thank you for this script :)

**Comment by deltaflyer4747** [comment]
great, Glad you like it :) 

Issue resolved, closing.
