### ISSUE TITLE
Only able to take 1 picture

### ISSUE THREAD

**Issue by marcos10soares** [deltaflyer4747/Xiaomi_Yi#11]
First of all thank you for your amazing work!

The problem that I am experiencing, is after connecting to the camera I'm only able to take one picture, after that the camera becomes unresponsive.

I have tried with two different cameras, the problem is the same, also tried just using the command line with telnet 7878 and then sending the messages, also getting the same result.

telnet 172.20.10.13 7878
Trying 172.20.10.13...
Connected to 172.20.10.13.
Escape character is '^]'.
{"msg_id":257,"token":0}
{ "msg_id": 7, "type": "vf_stop" }{"msg_id":257, "param":2, "rval": 0 }{ "rval": 0, "msg_id": 257, "param": 1 }
{ "rval": 0, "msg_id": 257, "param": 2 }{ "msg_id": 7, "type": "battery" ,"param":"57"}{"msg_id":769,"token":2}
{"rval":0,"msg_id":769}{"msg_id":769,"token":2}
{"rval":-21,"msg_id":769}{"msg_id":257,"token":0}
{ "msg_id": 7, "type": "vf_stop" }{ "rval": 0, "msg_id": 257, "param": 2 }{"msg_id":769,"token":2}
{"rval":-21,"msg_id":769}{ "msg_id": 7, "type": "battery" ,"param":"56"}

this only resulted in one picture as well.

I think I am able to start recoding video (light starts flashing, but not able to stop it and also the camera becomes unresponsive)

Sometimes after sending the message to start recording the camera beeps loudly 3 times, and then resets.

**Comment by deltaflyer4747** [comment]
That may be caused by faulty/slow SD card
