### ISSUE TITLE
Which Yi Camera is this intended for ?

### ISSUE THREAD

**Issue by rasathus** [deltaflyer4747/Xiaomi_Yi#13]
There seems to be some quite confused people, judging by some of the other questions.

Is this intended for the Yi Action Camera, the GoPro like device , or the Yi Home Camera ?

**Comment by Tukks** [comment]
It's the yi action camera, and it works great.

**Comment by rasathus** [comment]
Thanks for clearing that up.  It might be worth an addition to the ReadMe.md .  Lots of the questions/issues sound like people confusing the two cameras.
