### ISSUE TITLE
show image after shot

### ISSUE THREAD

**Issue by BMo-design** [deltaflyer4747/Xiaomi_Yi#14]
Dear deltaflyer,
thank you for sharing that amazing project with us. I currently use your code to connect my raspberry pi with my Xiaomi Yi cam. Works fine.
I try to extend your Camera_photo.py script.
My aim is to display the photo that has been taken via pygame.
I figured out that the cam send some status updates that contain the image path on the cam:
See: https://gist.github.com/SkewPL/f57e6cff7fa14601f6b256926aa33437
But I can't figure out how to listen to that status updates. 
Till now I just get the "{"rval":0,"msg_id":769}" response via data = srv.recv(512).
Do you have any idea how I can listen to -> { "msg_id": 7, "type": "photo_taken" ,"param":"/tmp/fuse_d/DCIM/127MEDIA/YDXJ0373.jpg"}?
Thanks and best regards 
Ben

**Comment by deltaflyer4747** [comment]
iirc it only sends that info right after the shot is taken and you need to create a continuous listener for incoming messages.

btw... pygame? bit overkill, use PIL.Image and PIL.ImageTk within tkinter frames

```
                        from PIL import Image, ImageTk
                        image = Image.open("icons/%s" %self.weather)
                        image = image.resize((128, 144), Image.ANTIALIAS)
                        img = ImageTk.PhotoImage(image)
                        self.weatherFrame.config(image=img)
                        self.weatherFrame.image=img
```

**Comment by carlosnewmusic** [comment]
Then put a check with that option in the code
