### ISSUE TITLE
Cannot connect - Windows 10

### ISSUE THREAD

**Issue by carlosnewmusic** [deltaflyer4747/Xiaomi_Yi#17]
I have a Yi camera. I cloned this Github project and tried the python script CC.pyw/CC.exe on my Windows 10 pc, and when the UI comes up, it shows IP address, JSON port, etc. But after clicking the Connect C&C button, a window pops up that says "Cannot connect to the address specified".

Using python 3.5

**Comment by deltaflyer4747** [comment]
You have to connect to the camera's wifi first.

**Comment by carlosnewmusic** [comment]
I already did, connecting the camera's wifi first and then connecting from the computer; But I can not connect to the application

**Comment by andriyloboda** [comment]
same issue, connected to camera's wifi first then connect in program. error message appears "Cannot connect to the address specified"

**Comment by pfcoperez** [comment]
When your camera WiFi turns on, you need to join to the WiFi network it has
created before starting the application. Are you connected to the access
point that the camera has become after enabling network connectivity?

**Comment by carlosnewmusic** [comment]
Yes and I don't connect the aplicaction; after clicking the Connect C&C button, a window pops up that says "Cannot connect to the address specified".

**Comment by andriyloboda** [comment]
I join WiFi network created by camera first and then launch the app and press button Connect but it doesnt work, same message

**Comment by deltaflyer4747** [comment]
paste your ipconfig /all (or ip a if you are on linux) after you connect to camera network

**Comment by deltaflyer4747** [comment]
Also paste your camera fw version

**Comment by andriyloboda** [comment]
where can I see fw version?

**Comment by deltaflyer4747** [comment]
that computer is not connected to Yi's wifi network. You can tell that by looking at the "Dell Wireless 1702 802.11b/g/n" section that it does not have proper IP nor DHCP enabled, which is the standard for Yi.

Try resetting your camera to factory defaults (press the power button and the wifi button simultaneously, wait for several beeps with pauses).

**Comment by andriyloboda** [comment]
![2017-06-12_23-03-06](https://user-images.githubusercontent.com/12795839/27052747-5f028b6c-4fc3-11e7-9978-c205c82ee09b.png)

made reset, doesnt help

**Comment by deltaflyer4747** [comment]
well, your computer is not - for some reason - connecting to the network. Try typing "ipconfig /renew" in the commandline and see if the appropriate section changes afterwards in the ipconfig /all

**Comment by deltaflyer4747** [comment]
(and BTW this is not related to C&C, but your computer by itself)

**Comment by andriyloboda** [comment]
not only my computer

**Comment by deltaflyer4747** [comment]
Try to connect to the camera with your mobile phone and if you have an android, you can verify your IP by tapping the network name after you connect to it, it should show proper IP address starting with 192.168

It is also possible, that your camera or its firmware is faulty. Try reflashing the camera, you can easily & safely download firmware from my firmware mirror site at http://sw.deltaflyer.cz/CC/ - in case there are again issues with xiaomi official site.

**Comment by carlosnewmusic** [comment]
![captura](https://user-images.githubusercontent.com/19379457/27075417-59a9058a-502a-11e7-94d8-b9a669e86fe1.JPG)
![captura2](https://user-images.githubusercontent.com/19379457/27075424-5d48d2e2-502a-11e7-942e-2db7bd9863c5.JPG)
![captura3](https://user-images.githubusercontent.com/19379457/27075427-5f29cd64-502a-11e7-9c4e-83b719986fc8.JPG)
![captura4](https://user-images.githubusercontent.com/19379457/27075466-858a08e8-502a-11e7-952c-f814d8ef61a7.JPG)
177/5000
In the previous version of W10 does not work, in this if, first connect the camera by wifi removing the ethernet cable, and then with the camera connected I connect it and no error

**Comment by deltaflyer4747** [comment]
Yes, having the cable plugged while trying to connect to (any) wifi can cause issues on some computers. This is however not related only to XiaoYi, nor C&C, but is an general issue with windows networking.

**Comment by EricPaneth** [comment]
I have the a similar issue. ipconfig shows my IP to be 192.168.70. I ping OK 192.168.42.1 and do connect to 192.168.42.1 getting "Cannot connect....". CC.exe shows camera info, battery, ver. etc. but NO VIDEO.

**Comment by artromone** [comment]
> I have the a similar issue. ipconfig shows my IP to be 192.168.70. I ping OK 192.168.42.1 and do connect to 192.168.42.1 getting "Cannot connect....". CC.exe shows camera info, battery, ver. etc. but NO VIDEO.

Same problem on Windows and Linux both :(

**Comment by artromone** [comment]
> I have the a similar issue. ipconfig shows my IP to be 192.168.70. I ping OK 192.168.42.1 and do connect to 192.168.42.1 getting "Cannot connect....". CC.exe shows camera info, battery, ver. etc. but NO VIDEO.

Have you solved the problem?
