### ISSUE TITLE
Battery status does not update.

### ISSUE THREAD

**Issue by Berryfier** [deltaflyer4747/Xiaomi_Yi#2]
I suspect it is because at line 340 in CC.pyw the type should be battery_status; not battery.

**Comment by deltaflyer4747** [comment]
Unless they changed it in 1.1.0, it was working as it is. 

I don't have access to the camera atm, i have to wait when my cameras will arrive. BUT in the meanwhile i am creating different version of the app with different framework = basically i am rewriting whole app from the scratch :) (well, not entirely, internal functions stays almost intact)

**Comment by Berryfier** [comment]
Mine reports { "sw_version": "YDXJv22_1.0.2_build-20150309153416_b641_i446_s649" }
I'm still without courage to update!
Making the change worked for me.
Maybe you'll investigate once your camera arrives. 
Or perhaps someone else will look here if they notice the problem.

**Comment by deltaflyer4747** [comment]
oh, then they probably changed in later versions....i don't know, i don't have neither cams nor older firmwares available. But when i will, i will check it for sure.

**Comment by Berryfier** [comment]
I took courage and updated the firmware to 1.1.0. Your suspicions were right, the new firmware has type battery; not battery_status. The new firmware works with CC.pyw having line 340 as is. Thank you for looking after this.
