### ISSUE TITLE
Firmware 1.2+

### ISSUE THREAD

**Issue by bdunlay** [deltaflyer4747/Xiaomi_Yi#4]
Have you tried this with latest firmware? Doesn't seem to be accepting connections on port 7878 anymore.

**Comment by deltaflyer4747** [comment]
C&C is always tested with latest firmware, it works perfectly. Check your network connection (ping), 1.2 often freezes...

**Comment by bdunlay** [comment]
Thanks, you're right, must have frozen at the time.
