### ISSUE TITLE
Yi Camera Night Vision support

### ISSUE THREAD

**Issue by yacc143** [deltaflyer4747/Xiaomi_Yi#5]
1.) Is the new Night Vision Edition supported?
2.) How does one setup the camera initially (e.g. what Wifi it connects to)?

**Comment by deltaflyer4747** [comment]
"night vision" ? Sorry, i don't have any info about that.
You can use both client & original camera SoftAP modes.

**Comment by javl** [comment]
To answer your second question: the camera does not connect to any WIFI network: it creates its own network and your phone connects to that. See [this post](https://github.com/deltaflyer4747/Xiaomi_Yi/issues/8#issuecomment-135905451) as well.
