### ISSUE TITLE
Bug in def FileDownChunk()

### ISSUE THREAD

**Issue by luckylz2git** [deltaflyer4747/Xiaomi_Yi#6]
```
def FileDownChunk(self, chunk_size=0, report_hook=None, FileTP=""):
...
    towrite = ""
...
    towrite += chunk
...
    filek.write(chunk)
...
```
You use the "towrite" to keep file data get from YiCam, but final only write the last chunk to the downloaded file. Will you still keep update this repo?

**Comment by deltaflyer4747** [comment]
cosmetic issue, no effect on the function. Fixed, will be pushed in next release.

**Comment by deltaflyer4747** [comment]
implemented
