### ISSUE TITLE
Configuration window is blank

### ISSUE THREAD

**Issue by DeanCording** [deltaflyer4747/Xiaomi_Yi#7]
Since upgrading the camera firmware to 1.2.10 the configuration window in CC does not show any settings.

The following error message is shown:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1535, in __call__
    return self.func(*args)
  File "./CC.pyw", line 869, in MenuConfig
    ValueBox = OptionMenu(ThisFrame, ThisValue, *self.camsettableconfig[ThisOption])
TypeError: __init__() takes at least 4 arguments (3 given)
```

**Comment by deltaflyer4747** [comment]
Already reported, fixed with 0.6.10

**Comment by ajohnclark** [comment]
FYI just to share: I had same error with the recent 0.6.10 on Windows 8 after rather aggressively re-sizing the window a couple times (GUI kept going back to a fixed size) before clicking "Config". The config view was blank whenever I did this before; I tried again with a fresh WiFi-connect / no re-sizing and config view showed up fine. Great project, thank you!

**Comment by deltaflyer4747** [comment]
Not the same issue tho, thanks for the report anyway. It is true, that the size is hardcoded.
